version: "3"

services:
  aee_digital_regionais:
    environment:
      - NODE_ENV=development
    build: .
    command: npm start
    image: aee_digital_regionais
    container_name: aee_digital_regionais
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    depends_on:
      - "mongo"
      - "redis"
    links:
      - mongo
      - redis
    networks:
      - aee_digital_backend
      - aee_regional_db
    restart: always
  mongo:
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - "3010:27017"
    networks:
      - aee_regional_db
    restart: always
  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
      - mongo
    ports:
      - "30001:8081"
    networks:
      - aee_regional_db
    restart: always
  redis:
    image: redis
    command: redis-server --appendonly yes --port 6380
    ports:
      - "6380:6380"
    networks:
      - aee_digital_backend
    volumes:
      - ./data/cache:/var/lib/postgresql/data
    restart: always
  redis-commander-regionais:
    container_name: redis-commander-regionais
    hostname: redis-commander-regionais
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=redis:redis:6380
    ports:
    - "6381:8081"
    networks:
      - aee_digital_backend
networks:
  aee_digital_backend:
    name: aee_digital_backend
    driver: bridge
  aee_regional_db:
    name: aee_regional_db
    driver: bridge
