version: '3.1'
networks:
  aee_digital_backend:
    name: aee_digital_backend

services:
  aee_digital_regionais:
    environment:
      - NODE_ENV=development
      - DB_STRING_CONNECTION=${DB_STRING_CONNECTION}
      - PORT=${PORT}
    build: .
    command: npm start
    image: aee_digital_regionais
    container_name: aee_digital_regionais
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/usr/app
    depends_on:
      - "redis"
    links:
      - redis
    networks:
      - aee_digital_backend
    restart: always
  redis:
    image: redis
    command: redis-server --appendonly yes --port 6380
    ports:
      - "6380:6380"
    networks:
      - aee_digital_backend
    volumes:
      - ./data/cache:/var/lib/postgresql/data
    restart: always
  redis-commander-regionais:
    container_name: redis-commander-regionais
    hostname: redis-commander-regionais
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=redis:redis:6380
    ports:
      - "6381:8081"
    networks:
      - aee_digital_backend