version: "3"

services:
    db:
        image: mysql:5.7
        volumes:
          - "./.mysql-data/db:/var/lib/mysql"
        restart: always
        ports:
          - 3306:3306
        environment:
          MYSQL_ROOT_PASSWORD: aeepw
          MYSQL_DATABASE: aee
          MYSQL_USER: aee
          MYSQL_PASSWORD: aeepw
    adminer:
        image: adminer
        ports:
            - 8080:8080