name: Deploy to HostGator VPS

on:
  push:
    branches:
      - main

    tags:
      - v*

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: aee_digital_regionais

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "main" ] && VERSION=latest

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      PORT: "$DEV_PORT"
      DB_STRING_CONNECTION: "$DEV_DB_STRING_CONNECTION"
    steps:
      - uses: actions/checkout@v3

      - name: Setup SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
      - name: Use Environment Variable
        run: |
          echo "The DB_STRING_CONNECTION is $DEV_DB_STRING_CONNECTION"
          echo "The PORT is $DEV_PORT"

      - name: Deploy Docker Compose
        run: |
          sudo docker-compose up -d
    