version: "3"

services:
    angular-ui:
        build:
          context: .
        ports:
          - "4201:4201"
        container_name: angular-ui
        volumes:
           - .:/usr/src/app/app-ui
           - /usr/src/app/app-ui/node_modules